---
title: "L01 Review"
subtitle: "Data Science 3 with R (STAT 301-3)"
author: "Chaeli Place"
pagetitle: "L01 Chaeli Place"
date: today

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 4
    toc-location: left
    embed-resources: true
    code-fold: false
    link-external-newwindow: true

execute:
  warning: false

from: markdown+emoji
reference-location: margin
citation-location: margin   
---

::: {.callout-tip icon="false"}
## Github Repo Link
[L01 Github repo link](https://github.com/stat301-3-2026-spring/l01-review-chaeliplace2026.git)
:::

## Overview

The goal of this lab is to review machine learning/predictive modeling vocabulary and concepts covered in Data Science 2 with R (STAT 301-2).

## Questions

When completing the following questions ensure your solutions are neatly formatted and clearly indicated. Consider including diagrams/images in some of your solutions, if it helps to make things easier to describe/discuss.

### Question 1

Provide a brief outline/overview of the steps involved in a supervised machine learning process. Could provide this as a bulleted list. 

::: {.callout-tip icon="false"}
## Solution

- Split the data

- EDA on training data (check for imbalance, explore feature engineering)

- Defining resamples (fold training data)

- Defining preprocessing recipes, prep and bake

- Defining model specifications (engine and mode) with tuning parameters

- Storing tuning parameters, update when needed, define tuning grid

- Setting the workflow (recipe and model)

- Tuning the model grid (with resamples)

- Evaluating average performance across resamples

- Fitting the best model(s) on all training data

- Evaluating final model on the testing data

:::

### Question 2

Explain the difference between supervised and unsupervised learning.

::: {.callout-tip icon="false"}
## Solution

- Supervised learning: data is labeled, goal is predicting outcomes (regression, classification). There is a target variable that supervises the process.

- Unsupervised learning: data is unlabeled, goal is identifying patterns in the data rather than predicting outcomes. There is no outcome of interest, just understanding the structure of the data.

:::

### Question 3 

In general, we can classify a model by its purpose into 1 of the 3 categories below. Provide a brief description of the goals of these model classes.

#### Descriptive Models 

::: {.callout-tip icon="false"}
## Solution

Identifying trends from existing/past data, describing or illustrating structure in the data that is available

:::

#### Inferential Models

::: {.callout-tip icon="false"}
## Solution

Testing hypotheses about how/why variables influence an outcome variable, taking into account underlying assumptions to draw conclusions about relationships between variables

:::

#### Predictive Models

::: {.callout-tip icon="false"}
## Solution

Using data to make the best possible prediction on new data without really caring about how/why variables influence the outcome

:::

### Question 4 

We can further describe/classify predictive models by how they were derived or developed as being either mechanistic or empirically driven. 

#### Part (a)

What does it mean to be a mechanistic model?

::: {.callout-tip icon="false"}
## Solution

A model is built on mechanistic assumptions about how variables relate to each other or the outcome. For example, coefficients might be derived from literature or known scientific laws.

:::

#### Part (b)

What does it mean to be an empirically driven model?

::: {.callout-tip icon="false"}
## Solution

No assumptions are made about how variables relate to the outcome and the learning process is entirely driven by the observed data rather than building in scientific laws or principles.

:::

#### Part (c)

How does the mechanistic and empirically driven model terminology relate to the parametric and nonparametric model terminology? 

::: {.callout-tip icon="false"}
## Solution

Mechanistic and empirically driven refer to how the model is constructed, while parametric and nonparametric refer to the mathematical form of the model. While mechanistic models are often parametric and empirically driven models are often nonparametric, these categories do not perfectly overlap. However, mechanistic and parametric models both make assumptions, either about how variables relate to each other or about the form of the equation that describes the relationship of variables to the outcome. Empirically driven and nonparametric models don't make assumptions about these relationships or fit to an equation, instead relying only on the data. That is, mechanistic/parametric are more structured, and empirically driven/nonparametric are more flexible.

:::

#### Part (d)

In general, is a mechanistic or empirically driven model easier to interpret? Explain.

::: {.callout-tip icon="false"}
## Solution

A mechanistic model is easier to interpret usually because it incorporates known facts/assumptions into the modeling process, so it's easier to understand how the model learns and why you get the results you get. With empirically driven models, we don't necessarily understand what specific things in the data the model is learning from and how/why.

:::

#### Part (e)

How does mechanistic and empirically driven model terminology relate to the idea of model flexibility? That is, which would be more or less flexible than the other.

::: {.callout-tip icon="false"}
## Solution

Empirically driven models are more flexible because they don't make assumptions about the data and don't incorporate scientific laws, instead letting the data drive the model fitting.

:::

#### Part (f)

Describe the bias-variance trade-off when considering the use of a mechanistic or empirically driven model. 

::: {.callout-tip icon="false"}
## Solution

Mechanistic models tend to have lower variance but higher bias, meaning they are less susceptible to overfitting but make more assumptions that might overlook more complex patterns. Empirically driven models tend to have higher variance but lower bias, meaning they are more sensitive to noise/prone to overfitting but are better at finding/describing more complex patterns in the data.

:::

### Question 5 

Explain the difference between a regression and classification machine learning (ML) problems.

::: {.callout-tip icon="false"}
## Solution

Regression problems produce predictions for continuous numeric outcome variables, i.e. they return a specific numeric value. Classification problems produce predictions for discrete categorical outcome variables, i.e. they return a specific category.

:::

### Question 6 

When splitting the data, why is it useful to stratify by the outcome/target variable? 

::: {.callout-tip icon="false"}
## Solution

It ensures that we have all different classes or ranges of values represented in our smaller split datasets in the same proportion as the original dataset so that we don't accidentally create an imbalanced dataset or don't get good coverage of the range of possible values. It's especially important if we have a small class that might not be sufficiently represented in our splits if left to chance.

:::

### Question 7 

Briefly describe how v-fold cross validation with repeats is used to estimate test RMSE. Also provide an explanation of why we use it. 

::: {.callout-tip icon="false"}
## Solution

V-fold cross validation splits the data into a specified number of even groups (folds). One fold is reserved as the test set, and the remaining number acts as the training set. This is repeated until every fold has served as the test set. The data is again split into different folds for each repeat, and the whole process begins again. The performance metrics as determined by evaluation on the test set is averaged across all folds and repeats. This allows us to get an idea of how our model performs across different test datasets, which can help us identify issues like overfitting/high variance and have a more stable, accurate picture of how generalizable our model is.

:::

### Question 8

When might we use a bootstrap resampling procedure instead of v-fold cross validation to estimate test RMSE?

::: {.callout-tip icon="false"}
## Solution

Bootstrap resampling is better for small datasets because you could end up with insufficient testing data with v-fold cross validation and get very different train/test splits. Bootstrap performs more resamples and can reuse data to make the most of small datasets. 

:::

### Question 9 

Briefly describe model tuning and why we use it.

::: {.callout-tip icon="false"}
## Solution

Model tuning is used to optimize model hyperparameters by trying out a range of values for each hyperparameter and trying different combinations of hyperparameter values to find the combination that allows the model to perform the best. We use it because the values we choose for hyperparameters directly specifies how the model is built/how it learns, and defaults are usually not optimal and it is often difficult to pick optimal hyperparameters just by guessing, especially when we have multiple hyperparameters and could have many different combinations.

:::

### Question 10 

What are two common performance metrics when dealing with a regression ML problem?

::: {.callout-tip icon="false"}
## Solution

RMSE, MAE, R squared

:::

What are two common performance metrics when dealing with a classification ML problem?

::: {.callout-tip icon="false"}
## Solution

ROC AUC, accuracy

:::

### Question 11

Classify each question/problem below as either prediction or inferential. Explain your reasoning for each.

A company with a subscription based service (for example Netflix, Disney+, New York Times, etc) has data concerning customer interactions with a them, including features like the number of customer service calls, quality of service calls, subscription length, engagement with the service, discounted service, etc. They are interested in two questions:

1. Does a high number of service calls impact a customer's likelihood of churn in the next month (leave the company/drop the service)?

::: {.callout-tip icon="false"}
## Solution

Inferential. They want to know how a variable (number of service calls) affects the outcome; they are not interested just in predicting and outcome but want to test the hypothesis that this specific variable influences the outcome.

:::

2. How likely is it that a customer will churn in the next month (leave the company/drop the service)?

::: {.callout-tip icon="false"}
## Solution

Predictive. The goal is not to understand how or why different variables relate to the outcome but rather how they can be used to make an accurate prediction.

:::

